### ISSUE TITLE
Workflow question

### ISSUE THREAD

**Issue by supakeen** [mtkennerly/dunamai#1]
Hey there, thanks for this project!

The past time I've been slowly trying to learn about Python packaging, continuous integration, and other various things. As part of that I'm moving some of my projects to ``poetry``. For versioning I am using your library. I've used ``versioneer`` in the past.

My question regards to workflow, version numbers are automatically fetched from the closest parent tag in the commit graph (if I understand correctly). However this means I must first tag before using the commands to update my version in ``pyproject.toml`` and my projects ``_version.py``.

The problem here is that the tag needs to include the changes to these files so my current flow is mostly to tag a version, then update those files, then delete/re-tag and commit/push.

Is there a more sane way of doing this? I've seen the runtime dependency which would work for at least ``_version.py`` but not for ``pyproject.toml``.

How do you do this?

**Comment by mtkennerly** [comment]
Hello! I don't think you should commit the changes to pyproject.toml and _version.py. The committed values would just be placeholders like 0.0.0, since ultimately you only need the real version in the published artifacts. All you need is a script like an [Invoke](http://www.pyinvoke.org) task to do something like this:

```python
from invoke import task
from dunamai import Version

@task
def build(ctx):
    version = Version.from_git().serialize()
    ctx.run("echo __version__ = '{}' > _version.py".format(version))
    ctx.run("poetry version {}".format(version))
    ctx.run("poetry build")
    ctx.run("git checkout -- .")
```

Then the workflow would be:

* Make the tag.
* Run `invoke build` instead of `poetry build` to create an artifact with the new version.

Since you're using Poetry specifically, you may want to check out [poetry-dynamic-versioning](https://github.com/mtkennerly/poetry-dynamic-versioning) (I'm also the author). It doesn't currently create/modify _version.py, but I do plan to add that.

**Comment by supakeen** [comment]
Hey, thank you! poetry-dynamic-versioning is exactly the way I'd have expected things to work. I'll be using that and probably taking a look at it to add the 'replace placeholder in files' myself.

If I have any questions I'll contact you there, thanks again.
