### ISSUE TITLE
Does not find new tags (made on same day?)

### ISSUE THREAD

**Issue by tbsexton** [mtkennerly/dunamai#3]
Found this super useful tool via `poetry-dynamic-versioning`.

However, after working the first time, subsequent builds failed to add the patch version, instead adding revisions to my first patch. 

`git describe --tags` returns `0.1.4`, but running `dunamai from git` returns `0.1.1.post8.dev0+9838662f09`. Did some digging and the command I found [here](
https://github.com/mtkennerly/dunamai/blob/dc2777cdcc5eeff61c10602e33b1a0dc0bb0357b/dunamai/__init__.py#L313) returns these tags:

```
0.1.4
0.1.3
0.1.2
v0.1.1
0.1.1
```
Is that the right order? [This](https://stackoverflow.com/a/34919313) answer seems to use the same/similar syntax, but in reverse order.

**Comment by tbsexton** [comment]
OH! apologies....I deleted all tags missing "v" from the beginning, after trying to only delete the "mistake" one that had it. Then _nothing_ was returned by dunamais. 

Now, tagging with a `v`, all seems to be working correctly. 

Still, it's [my understanding](https://github.com/semver/semver/issues/204) that semver doesn't actually require the `v`. Is this desired behaviour?

**Comment by mtkennerly** [comment]
Hello! I made the default configuration require the `v` prefix since that's the most prevalent tagging convention I've seen among open source projects. The `v` isn't part of the version itself (Dunamai's output does not include it) and so isn't subject to SemVer, but it's used on the input to help avoid false positive tag matches. Since Dunamai supports other output formats than SemVer and since tags don't have to conform to the output format anyway, you might end up with a tag like simply `1` getting picked up as a version, which I wouldn't feel confident enough about. All that said, you can use `--pattern` to avoid the `v` prefix if you prefer.

**Comment by tbsexton** [comment]
Great, thanks for the clarification! I'll mark this closed since it's by-design. 

For the sake of others, is there maybe a way to report when only a subset of tags are getting matched? Before deleting the single tag having a `v` prefix, dunamai happily chugged along only returning that one. I only figured out the issue after deleting that tag, which returned the fuii list of "false negatives": 

```
$ dunamai from git
Pattern '^v(?P<base>\d+\.\d+\.\d+)(-?((?P<stage>[a-zA-Z]+)\.?(?P<revision>\d+)?))?$' did not match any tags from ['0.1.4', '0.1.3', '0.1.2', '0.1.1']
```

Since this is human error, and ostensibly our intention under dynamic versioning is to match all of the tags (which dunamai has access to a priori), couid a debug flag be added that reports tag _subsets_ that failed to match the given pattern?

**Comment by mtkennerly** [comment]
Good idea; I'll look into adding something like that. I could imagine having some output on stderr like:
```
Matched tag: v0.1.1
Newer unmatched tags: 0.1.4, 0.1.3, 0.1.2
```
