### ISSUE TITLE
using CalVer

### ISSUE THREAD

**Issue by zacharyburnett** [mtkennerly/dunamai#49]
What would be the best way to use `dunamai` for getting a calendar version with [CalVer](https://calver.org)?

**Comment by mtkennerly** [comment]
Since Dunamai just operates on VCS tags, you can use CalVer (or any system you like) when you create your tags, and then Dunamai will use them as-is. For example, a tag like `v2022.08.01` or `v8.1` would be recognized with the default config. As long as the tag matches Dunamai's tag `--pattern` (which can be customized), then it'll work.

The `--bump` functionality wouldn't be applicable to CalVer, but everything else should be.

**Comment by zacharyburnett** [comment]
ah ok, thank you! That is simple!
