### ISSUE TITLE
Could not properly parse with Version.parse

### ISSUE THREAD

**Issue by mzebrak** [mtkennerly/dunamai#57]
Looks like Version.parse could not properly parse 

A minimal working example showing mentioned behaviour is:
`dunamai.Version.parse(dunamai.Version.from_git().serialize())`

result of the following command:
```
{
    "base": "0.0.0.post341.dev0+5d7b186",
    "stage": None,
    "revision": None,
    "distance": 0,
    "commit": None,
    "dirty": None,
    "tagged_metadata": None,
    "epoch": None,
    "branch": None,
    "timestamp": None,
    "_matched_tag": None,
    "_newer_unmatched_tags": None
}
```

From what i get, it should parse (since by default it uses Pattern.DEFAULT) to something like:
```
{
    "base": "0.0.0",
    "stage": None,
    "revision": None,
    "distance": 341,
    "commit": "5d7b186",
    "dirty": True,
    "tagged_metadata": None,
    "epoch": None,
    "branch": None,
    "timestamp": None,
    "_matched_tag": None,
    "_newer_unmatched_tags": None
}
```

**Comment by mtkennerly** [comment]
Thanks for bringing this up. I can add some special handling for parsing versions with `.post0.dev0`.

**Comment by mzebrak** [comment]
That would be great, i appreciate it.

Currently in the project where I came across it - I want to be able to install the project from source (via poetry install) but I dont want to get any additional actions from the user like it is required in the poetry-dynamic-versioning plugin (it has to be included in poetry self dependencies) so  I came up with the idea of ​​using poetry dynamic-versioning along with dunamai. It boils down to the condition - when git is installed -> use dunamai to determine the version, and when it is not available (I assume someone will be installing the project from PyPI so some artifacts, like .whl will be available), use the included version thanks to the poetry- dynamic versioning.

For this reason I wanted to parse the substitution placed by poetry-dynamic-versioning to have easy access to the commit sha. What do you think? As the author of both of these projects, maybe you have some insights? (I care about a simple installation both from sources and the ability to build artifacts containing an already loaded version)

**Comment by mtkennerly** [comment]
Do you strictly need to do the source install using `poetry install`? If you want to avoid any extra setup on the user's end, then all they need to do is `pip install .` or `pip install git+https://...`. That way, they don't even need to install Poetry, since Pip will take care of installing whatever's in the `build-system` section of pyproject.toml (i.e., Poetry Core and poetry-dynamic-versioning).

In that case, it would only be the project's own contributors who would get a dummy version (from running `poetry install`), and I'm not sure why that would matter too much in a purely development environment. Is there some code path or API field that needs to know the active version?

**Comment by mzebrak** [comment]
> Do you strictly need to do the source install using poetry install?

Nope, pip is fine too. I just want to give the user the ability to install from sources, then substituting files should work and I can show them the current version when they run the app.

##

Yes, there are several places in the code where I need to get the current version. I actually didn't know that `pip install .` would work when `poetry install` didn't, but I checked it anyway, with no plugin added, it's correct (somekind). What is strange - I can see that the project is installed with the correct version, but file substitution is not performed.


My configuration:
```
[build-system]
requires = ["poetry-core>=1.0.0", "poetry-dynamic-versioning"]
build-backend = "poetry_dynamic_versioning.backend"


[tool.poetry]
name = "dynamic"
version = "0.0.0"
description = ""
authors = [""]
packages = [{ include = "dynamic" }]


[tool.poetry.dependencies]
python = "^3.10"


[tool.poetry-dynamic-versioning]
enable = true
format = "v{base}+{distance}{dirty}.{commit}"

[tool.poetry-dynamic-versioning.substitution]
files = ["dynamic/__init__.py"]
```

Here are some cases:
### Without `poetry-dynamic-versioning` installed in poetry self dependencies
   * via poetry
   ```
   > poetry install
   Installing the current project: dynamic (0.0.0)
   >  python -c "import dynamic; print(dynamic.__version__)"
   0.0.0
   ```
   * via pip
   ```
   > pip install .
   Successfully installed dynamic-0.0.1+0dirty.7d87256
   >  python -c "import dynamic; print(dynamic.__version__)"
   0.0.0  # We got a problem here. I want user be able to view the actual version when he runs the application.
   ```
  ### With `poetry-dynamic-versioning` installed in poetry self dependencies
   * via poetry
   ```
   > poetry install
   Installing the current project: dynamic (v0.0.1+0dirty.7d87256)
   >  python -c "import dynamic; print(dynamic.__version__)"
   0.0.0  # I understand that as I already read https://github.com/mtkennerly/poetry-dynamic-versioning/issues/25
   ```
   * via pip
   ```
   > pip install .
   Successfully installed dynamic-0.0.1+0dirty.7d87256
   >  python -c "import dynamic; print(dynamic.__version__)"
   0.0.0  # We got a problem here. I want user be able to view the actual version when he runs the application.
   ```
   
   * and to check if my configuration is correct:
   ```
   > poetry dynamic-versioning
   > python -c "import dynamic; print(dynamic.__version__)"
   v0.0.1+0dirty.7d87256
   ```

**Comment by mtkennerly** [comment]
I have a feeling that's related to the plugin's cleanup logic. It reverts the file substitutions before Poetry exits, which is fine when you're just building an sdist or a wheel. However, it would seem that `pip install .` is doing something different (I assume an editable install), so the changes get reverted too early.

It works when installing from a URL:

```
$ pip install git+https://github.com/mtkennerly/playground
Successfully installed dummy-python-project-0.1.0.post8.dev0+d3a036f

$ python -c "import dummy_python_project"
loaded dummy project version 0.1.0.post8.dev0+d3a036f
```

But it doesn't work with `pip install .`:

```
$ pip install .
Successfully installed dummy-python-project-0.1.0.post8.dev0+d3a036f

$ python -c "import dummy_python_project"
loaded dummy project version 0.0.0
```

I think I can fix it by adding a flag to the build backend's `build_editable` function, but I'll need to try it and make sure it works.

**Comment by mzebrak** [comment]
As far as I know, the project should not be installed in editable mode (pip of course, as in poetry it's the default) unless you explicitly specify --editable (or -e). So it should be installed in an editable mode only with ` pip install -e .` and not with `pip install .`

**Comment by mtkennerly** [comment]
You're right; Pip seems to use the `build_wheel` hook from the build backend during `pip install .`.

I did some more testing and realized that my results above were incorrect. The reason `pip install .` and then `python -c "import dummy_python_project"` produced 0.0.0 was because I was still in the project directory, so it imported the code from the working tree rather than from the installed copy.

When I change directories, it works correctly:

```
$ pip install .
Successfully installed dummy-python-project-0.1.0.post8.dev0+d3a036f

$ python -c "import dummy_python_project"
loaded dummy project version 0.0.0

$ cd /tmp

$ python -c "import dummy_python_project"
loaded dummy project version 0.1.0.post8.dev0+d3a036f
```

I think that also explains the `via pip` result in your `With poetry-dynamic-versioning installed in poetry self dependencies` test.

**Comment by mzebrak** [comment]
But the `cd` solution looks like a hacky workaround. I certainly wouldn't want to include information in the source installation instructions that despite creating the python virtual environment in the folder with the cloned project, activating it and installing the project in it, after all this you need to cd somewhere outside for versioning to work.

What about:
> I think I can fix it by adding a flag to the build backend's build_editable function, but I'll need to try it and make sure it works

Is there an option to introduce some flag, which, when included in the pyproject.toml file, would always make the version inserted into the file during installation? Even as editable? I like this option because it gives the users of your library a choice.

**Comment by mtkennerly** [comment]
I wouldn't consider it a hack. Python itself gives higher priority to importing modules from the working directory before importing them from site-packages. If the module exists in multiple places, then Python has a standard way of resolving it and choosing one.

For users who want to install from the repository directly, you could recommend that they let Pip handle the clone (`pip install git+https://...`) so that they don't temporarily have a duplicate module name in their working directory. That said, I think a wheel or sdist is still the most streamlined option for normal users, which also has the benefit of the plugin injecting a static version into the wheel/sdist produced by `poetry build`.
